taxi_rides_ny:
  outputs:
    dev:
      dataset: trips_data_all
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/apple/.creds/dbt-user-creds.json
      location: US
      method: service-account
      priority: interactive
      project: arthur-data-engineering-course
      threads: 4
      type: bigquery
  target: dev

elementary:
  outputs:
    default:
      type: bigquery
      project: arthur-data-engineering-course
      dataset: trips_data_all_elementary
      method: service-account
      keyfile: /tmp/bigquery_keyfile.json
      threads: 4